name: 'Publish'

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  sbt_publish:
    name: 'SBT Publish'
    runs-on: ubuntu-latest
    environment: production
    container: hseeberger/scala-sbt:11.0.12_1.5.5_2.13.6
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
      - name: sbt compile
        run: sbt compile
      - name: sbt publish
        run: sbt publish